#include "__cf_friccion_aislada_esferica_Simscape_Symmechanics.h"
#ifndef RTW_HEADER_friccion_aislada_esferica_Simscape_Symmechanics_types_h_
#define RTW_HEADER_friccion_aislada_esferica_Simscape_Symmechanics_types_h_
#endif
